- path: '/'
  destination: 'https://www.signalnerve.com'
- path: '/twitter'
  destination: 'https://twitter.com/signalnerve'
- path: '/youtube'
  destination: 'https://www.youtube.com/channel/UCGNMFbZq5LHXj2sq5pUThcw'
- path: '/github'
  destination: 'https://www.github.com/signalnerve'
- path: '/youtube/rails'
  destination: 'https://www.youtube.com/playlist?list=PLNBxWcmM4zedLWU-99_52nbsXZGkwSwa9'
- path: '/youtube/git'
  destination: 'https://www.youtube.com/watch?v=r9Oi6sXb054&list=PLNBxWcmM4zefK1l1jXZJ7D2XxWd5EmIom'
- path: '/soundcloud'
  destination: 'https://soundcloud.com/kristianfreeman'
